import type { Notice, SetuNoticeItem } from '@/types';

// ─── Student Corner Notice Board Data ────────────────────────────────────────
// Replace with real API fetch once backend is ready (see API_ENDPOINTS.notices)
export const NOTICES: Notice[] = [
  {
    id: 1,
    type: 'exam',
    title: 'End-Term Time-Table Even Semester 2025 — F.No. AE814',
    body: 'End-term examination timetable for Even Semester 2025 has been notified. Check the official portal for department-wise schedule. All students must download their admit card from Samarth portal.',
    url: 'https://www.cusb.ac.in/index.php?option=com_content&view=article&id=77&Itemid=192',
    pdfUrl: 'https://www.cusb.ac.in/images/2025/sem_exam/may_25/timetable_even_2025.pdf',
    date: '1 May 2025',
    isNew: true,
  },
  {
    id: 2,
    type: 'exam',
    title: 'Revised Time-Table End-Term Exam Even Sem 2025 — Continuation AE814',
    body: 'Revised exam timetable for Even Semester 2025. Supersedes original AE814 for affected departments. Check official portal for latest dates.',
    url: 'https://www.cusb.ac.in/index.php?option=com_content&view=article&id=77&Itemid=192',
    date: '10 May 2025',
    isNew: true,
  },
  {
    id: 3,
    type: 'result',
    title: 'M.A. English 2nd Semester Result Session 2024-26 — F.No. AE-1081 dt. 20.06.2025',
    body: 'Result declared for M.A. English 2nd Semester Session 2024-26. File No. CUSB/Acad/44-375/2024/AE-1081. Re-evaluation applications within 15 days.',
    url: 'https://cusb.ac.in/index.php?Itemid=194&id=79&option=com_content&view=article',
    pdfUrl: 'https://www.cusb.ac.in/images/2025/sem_exam/may_25/206.pdf',
    date: '20 Jun 2025',
    isNew: true,
  },
  {
    id: 4,
    type: 'result',
    title: 'All Semester Results 2025 — UG, PG & Ph.D. Programmes',
    body: 'Semester results for all programmes on official results page and Samarth portal. Re-evaluation and re-checking within 15 days. Provisional marksheets on Samarth. Contact examination section for original marksheets.',
    url: 'https://cusb.ac.in/index.php?Itemid=194&id=79&option=com_content&view=article',
    date: 'Mar 2025',
    isNew: false,
  },
  {
    id: 5,
    type: 'notice',
    title: 'Academic Calendar AY 2025-26 Ongoing PG Batches — F.No. AE1135 dt. 04.07.2025',
    body: 'Academic calendar for ongoing PG students AY 2025-26. Semester start/end, exam schedule, holidays. F.No. AE1135 dated 04.07.2025.',
    url: 'https://cusb.ac.in/index.php?Itemid=191&id=76&option=com_content&view=article',
    date: '4 Jul 2025',
    isNew: false,
  },
  {
    id: 6,
    type: 'notice',
    title: 'Academic Calendar AY 2025-26 Newly Admitted PG Students — F.No. AE1136 dt. 04.07.2025',
    body: 'Academic calendar for newly admitted PG students AY 2025-26. Orientation, course registration, mid-sem and end-term dates. F.No. AE1136 dated 04.07.2025.',
    url: 'https://cusb.ac.in/index.php?Itemid=191&id=76&option=com_content&view=article',
    date: '4 Jul 2025',
    isNew: false,
  },
  {
    id: 7,
    type: 'exam',
    title: 'Academic Calendar AY 2025-26 (Jul-Dec) UG & B.Lib — F.No. AE1344 dt. 14.08.2025',
    body: 'Academic calendar UG and B.Lib.I.Sc. programmes July–December 2025. Odd semester dates. F.No. AE1344 dated 14.08.2025.',
    url: 'https://cusb.ac.in/index.php?Itemid=191&id=76&option=com_content&view=article',
    date: '14 Aug 2025',
    isNew: false,
  },
  {
    id: 8,
    type: 'download',
    title: 'PG Admission Notification 2026-27 — Seat Matrix & Eligibility',
    body: 'PG Admission Notification 2026-27. Programme-wise seat matrix, eligibility criteria, CUET-PG score requirements, counselling schedule, fee structure. Official notification released by CUSB.',
    url: 'https://www.cusb.ac.in/index.php?option=com_content&view=article&id=897&Itemid=690',
    date: 'May 2026',
    isNew: true,
  },
  {
    id: 9,
    type: 'download',
    title: 'Student Forms — Exam, Migration, TC, Bonafide, Character Certificate',
    body: 'All student forms for download: Examination enrolment, Migration certificate, Transfer certificate, Bonafide, Character certificate, No-dues, Re-evaluation application. Submit to examination section.',
    url: 'https://www.cusb.ac.in/index.php?option=com_content&view=article&id=445&Itemid=591',
    date: '2025',
    isNew: false,
  },
  {
    id: 10,
    type: 'download',
    title: 'Open Elective Courses List — Even Semester Jan-June 2025',
    body: 'Open elective courses Even Semester Jan-June 2025. Register via Samarth portal. Inter-departmental electives. Max 2 electives per semester.',
    url: 'https://cusb.ac.in/index.php?Itemid=195&id=119&option=com_content&view=article',
    date: 'Jan 2025',
    isNew: false,
  },
  {
    id: 11,
    type: 'scholar',
    title: 'National Scholarship Portal (NSP) — Central Government Scholarships',
    body: 'NSP for all central government scholarships. Central Sector Scheme for students with family income below Rs 4.5 lakh. Post-Matric for SC/ST/OBC. Required: Aadhaar, bank passbook, income certificate, marksheet. Apply at scholarships.gov.in.',
    url: 'https://scholarships.gov.in/',
    date: 'Ongoing',
    isNew: true,
  },
  {
    id: 12,
    type: 'scholar',
    title: 'Bihar State Scholarship — e-Kalyan Portal, Government of Bihar',
    body: 'Bihar scholarships for BC-EBC, OBC, SC, ST students. Pre and post matric. Apply at ekalyan.bih.nic.in. Documents: Aadhaar, bank account, income certificate, caste certificate, marksheet.',
    url: 'https://ekalyan.bih.nic.in/',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 13,
    type: 'scholar',
    title: 'INSPIRE Scholarship (DST) for Science Students at CUSB',
    body: 'INSPIRE for B.Sc. and Integrated M.Sc. top 1% Class XII students. Rs 80,000 per year. Apply at online-inspire.gov.in.',
    url: 'https://online-inspire.gov.in/',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 14,
    type: 'scholar',
    title: 'UGC-JRF Fellowship for Ph.D. Students at CUSB',
    body: 'UGC-JRF for PhD students who cleared NET-JRF. Stipend Rs 37,000/month (JRF), Rs 42,000/month (SRF). 5-year tenure. Apply through university research section.',
    url: 'https://cusb.ac.in/',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 15,
    type: 'hostel',
    title: 'Hostel Allotment Notice — Boys & Girls Hostels AY 2025-26',
    body: 'Hostel allotment AY 2025-26. Boys 500 seats, Girls 300 seats. Merit-cum-need basis. Fee Rs 8,000/semester (Rs 3,000 refundable). Documents: admission letter, fee receipt, 2 passport photos, medical certificate. DSW: dsw@cusb.ac.in',
    url: 'https://cusb.ac.in/index.php?option=com_content&view=article&id=20&Itemid=124',
    date: 'Jul 2025',
    isNew: true,
  },
  {
    id: 16,
    type: 'hostel',
    title: 'Hostel Facilities, Rules & Anti-Ragging Policy at CUSB',
    body: 'Facilities: Wi-Fi, reading room, laundry, medical, gym, CCTV. Rules: curfew 10 PM, no outside guests. Anti-ragging helpline UGC 1800-180-5522 toll-free 24×7. Complaint: antiragging.in. Violation = expulsion.',
    url: 'https://cusb.ac.in/index.php?option=com_content&view=article&id=20&Itemid=124',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 17,
    type: 'placement',
    title: 'CUSB Career Fair 2025 — Training & Placement Cell Campus Drive',
    body: 'Career Fair 2025 at Multipurpose Hall. 30+ companies. IT, Banking, Education, FMCG, Research. Final year UG/PG eligible. Pre-register at placement@cusb.ac.in. Mock interviews and resume sessions provided.',
    url: 'https://cusb.ac.in/',
    date: 'May 2025',
    isNew: true,
  },
  {
    id: 18,
    type: 'placement',
    title: 'Training & Placement Cell CUSB — Internship & Job Opportunities',
    body: 'T&P Cell for campus recruitment, internships, career development. Mock interviews, resume workshops, soft skills training. Past recruiters: Wipro, HDFC, SBI, ICICI, Infosys. Contact placement@cusb.ac.in.',
    url: 'https://cusb.ac.in/',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 19,
    type: 'notice',
    title: 'NIRF Ranking 2025 — CUSB National Institutional Ranking Framework',
    body: 'CUSB ranked in NIRF 2025 University category. Ministry of Education rankings. Parameters: Teaching, Research, Graduation Outcomes, Outreach, Perception.',
    url: 'https://cusb.ac.in/index.php?option=com_content&view=article&id=679&Itemid=637',
    date: 'Jun 2025',
    isNew: true,
  },
  {
    id: 20,
    type: 'notice',
    title: 'CUET 2026 — Common University Entrance Test UG & PG Admissions (NTA)',
    body: 'CUET-UG for UG admissions, CUET-PG for PG admissions. Conducted by NTA. Register at exams.nta.ac.in. CUSB accepts CUET scores for PG only.',
    url: 'https://exams.nta.ac.in/CUET-UG/',
    date: '2026',
    isNew: true,
  },
  {
    id: 21,
    type: 'notice',
    title: 'Anti-Ragging Policy & Helpline — CUSB Zero Tolerance',
    body: 'Zero tolerance for ragging. Helpline 1800-180-5522 toll-free 24×7. Complaint antiragging.in. Declaration form mandatory at admission. Violation = FIR + expulsion.',
    url: 'https://antiragging.in/',
    date: 'Ongoing',
    isNew: false,
  },
  {
    id: 22,
    type: 'notice',
    title: 'Samarth Student ERP Portal CUSB — Results, Forms, Fee Payment',
    body: 'Samarth ERP for CUSB students. Features: course registration, fee payment, exam form, result view, scholarship application, hostel registration. Login at cusbadm.samarth.edu.in. IT support: it@cusb.ac.in',
    url: 'https://cusbadm.samarth.edu.in',
    date: 'Ongoing',
    isNew: false,
  },
];

// ─── Chatbot knowledge base (CUSB Setu) ──────────────────────────────────────
export const SETU_NOTICES: SetuNoticeItem[] = NOTICES.map((n) => ({
  t: n.type,
  ti: n.title,
  b: n.body,
  u: n.url,
  p: n.pdfUrl,
  d: n.date,
  n: n.isNew,
}));

export const SETU_TICKERS = [
  '📢 Admission 2026-27 open for PG via CUET-PG 2026',
  '📅 End-Term Time-Table Even Sem 2025 notified — Notice AE814',
  '📊 M.A. English 2nd Semester Result declared — F.No. AE-1081',
  '📥 PG Admission Notification 2026-27 released — apply via CUET-PG 2026',
  '🏆 NIRF Ranking 2025 — CUSB ranked in University category',
  '🎓 NSP Scholarship open — Apply at scholarships.gov.in',
  '💼 CUSB Career Fair 2025 — 30+ companies — Register now',
] as const;

// Quick-access cards for Student Corner landing
export const QUICK_ACCESS = [
  { icon: '📢', label: 'Notices',       sub: 'Latest circulars',    tab: 'notices',     color: '#fef3c7', textColor: '#92400e' },
  { icon: '📅', label: 'Exam Schedule', sub: 'Timetables',          tab: 'exam',        color: '#dbeafe', textColor: '#1e40af' },
  { icon: '📊', label: 'Results',       sub: 'Semester results',    tab: 'result',      color: '#d1fae5', textColor: '#065f46' },
  { icon: '📥', label: 'Downloads',     sub: 'Forms & PDFs',        tab: 'download',    color: '#ede9fe', textColor: '#5b21b6' },
  { icon: '🎓', label: 'Scholarships',  sub: 'Fellowships & aid',   tab: 'scholar',     color: '#f3e8ff', textColor: '#6b21a8' },
  { icon: '🏠', label: 'Hostel',        sub: 'Allotment & rules',   tab: 'hostel',      color: '#fce7f3', textColor: '#9d174d' },
  { icon: '💼', label: 'Placement',     sub: 'Campus drives',       tab: 'placement',   color: '#ecfdf5', textColor: '#047857' },
  { icon: '🛡️', label: 'Anti-Ragging', sub: 'Helpline 1800-180-5522', tab: 'all',      color: '#fef2f2', textColor: '#991b1b' },
] as const;
